name: default

data_dir: data
log_dir: logs_debug

text_extraction:
  chunk_size: 256
  chunk_overlap: 64
  doc_dir: doc_dir

mineral_system: 
  prompts_dir: mineral_system/prompts
  response_dir: mineral_system/response

  llm_config:
    llm_model: gpt-3.5-turbo
    llm_temperature: 0
    templates:
      system: You are an expert geologist.
      user: |
        For a region to be prospective for mineral deposits now, it must necessarily show evidence for all the critical ingredients required for the formation and preservation of those deposits:
        1. source: source(s) of ore components, transporting fluids, and energy to drive the system
        2. pathway: conduit(s) along which metals and fluids were transported from source to sink
        3. trap: physical and/or chemical mechanism(s) that deposited ore components at the sink
        4. preservation: processes permitting preservation of mineralization in the crust up to the present time

        Here is a paragraph from an academic paper:
        {context_str}

        Is this paragraph talking about any of the mineral system components? If not, simply answer with 'no', otherwise, choose one out of the four options below:
        A. source
        B. pathway
        C. trap
        D. preservation

        Your answer: 

mappable_criteria:
  prompts_dir: mappable_criteria/prompts
  response_dir: mappable_criteria/response

  llm_config:
    llm_model: gpt-3.5-turbo-16k
    llm_temperature: 0
    deposit_type: MVT
    definition:
      source: source(s) of ore components, transporting fluids, and energy to drive the system
      pathway: conduit(s) along which metals and fluids were transported from source to sink
      trap: physical and/or chemical mechanism(s) that deposited ore components at the sink
      preservation: processes permitting preservation of mineralization in the crust up to the present time

    # templates:
    #   system: You are an expert geologist.
    #   user: |
    #     For a region to be prospective for mineral deposits now, it must necessarily show evidence for critical ingredients required for the formation and preservation of those deposits.
    #     One of the critical ingredients is {component}. The definition for {component} is {definition}.
    #     Here are some paragraphs found in an academic paper that might be related to the {component} of the {deposit} deposit type:
    #     {context_str}

    #     Summarize the paragraphs above into a list of mappable proxies that represent the geological features.
    #     Answer: 
    templates:
      system: You are an expert geologist.
      user: |
        For a region to be prospective for mineral deposits now, it must necessarily show evidence for critical ingredients required for the formation and preservation of those deposits.
        One of the critical ingredients is {component}. The definition for {component} is {definition}.
        
        These formation processes generally are not observable directly for the mineral systems being investigated, and so for the purposes of spatial modelling it needs to be translated into one or more observable and mappable geological features, which are called 'mappable criteria'.

        Here is a paragraph from an academic paper that might be related to the {component} of the {deposit} deposit type:
        {context_str}

        Summarize the paragraph above into a mappable proxy that represent the geological features.
        Answer: 

output:
  schema_dir: schema