[vars]
sys_ver = 'v1.6'
data_dir = '../workdir-data'

[endpoints]
cdr_cmas = 'https://api.cdr.land/v1/prospectivity/cmas'
cdr_push = 'https://api.cdr.land/v1/prospectivity/datasource'

[params]
percentile_threshold_min = 80
percentile_threshold_default = 90
raster_height = 500
raster_width = 500
map_base = 'Cartodb Positron'
map_polygon_opacity = 0.8
emb_model_list = ["iaross/cm_bert", "Alibaba-NLP/gte-large-en-v1.5"]
