systems_dict = {
    'porphyry_copper': {
        'deposit_type': 'porphyry copper',
        'synonyms': 'Calcalkaline porphyry',
        'commodities': 'Cu, Mo, Au, Ag',
        'description': 'Porphyry copper deposits consist of disseminated copper minerals and copper minerals in veins and breccias that are relatively evenly distributed in large volumes of rock, forming high tonnage (>100 Mt), low to moderate grade (0.3–2.0 wt.% Cu) ores. Host rocks are altered and genetically related granitoid porphyry intrusions and adjacent wall rocks.',
        'rock_types': 'Tonalite to monzogranite or syenitic porphyry intruding granitic, volcanic, calcareous sedimentary, and other rocks.',
        'textures': 'Porphyry has closely spaced phenocrysts and microaplitic quartz-feldspar groundmass.',
        'age_range': 'Mainly Mesozoic and Cenozoic, but may be any age.',
        'depositional_environment': 'High-level intrusive complexes that commonly include stocks, dikes, and breccia pipes. Many deposits are focused in swarms of porphyry dikes that may radiate from larger intrusions or batholiths. The deposits form at shallow (mostly 6 km or less) depth by fluids exsolved from underlying crystallizing magmas emplaced at greater than 3–10-km depth in the upper crust and by external waters heated by those magmas',
        'tectonic_setting': 'Localized in time and space within magmatic arcs along convergent plate margins where subduction of oceanic crust and arc-type magmatism generates hydrous, oxidized upper crustal granitoids genetically related to ores. Arc crust is relatively thick, and there is evidence for broadly coeval compressional or transpressional tectonism',
        'ore_mineralogy': 'Hypogene: Chalcopyrite+pyrite±molybdenite; chalcopyrite+magnetite±bornite± Au; assemblages may be superposed. Quartz+K-feldspar+biotite±anhydrite; quartz+sericite+clay minerals. Late veins of enargite, tetrahedrite, galena, sphalerite, and barite in some deposits. Supergene: brochantite, copper pitch, cuprite, native copper, tenorite, chrysocolla, neotocite, malachite, and atacamite.',
        'alteration': 'Major alteration types are (1) potassic, (2) sericitic, (3) advanced argillic, (4) intermediate argillic, (5) propylitic, (6) sodiccalcic and sodic, (7) greisen, and (8) skarn. Weathering can form an enriched oxide zone above sulfide ore.',
        'ore_controls': 'Stockwork veins in porphyry, along porphyry contact, and in favorable country rocks such as carbonate rocks, mafic igneous rocks, and older granitic plutons.',
        'geochemical_signatures': 'Cu+Mo±Au+Ag+W+B+Sr center, Pb, Zn, Au, As, Sb, Se, Te, Mn, Co, Ba, and Rb outer. Locally Hg and Sn form most distal anomalies. High S in all zones. Some deposits have weak U anomalies.',
        'geophysical_signature': 'Ore zones can be associated with magnetite-rich rocks and are indicated by magnetic surveys. Intensely hydrothermally altered rocks, with quartz-pyrite-sericite (phyllic) alteration produce magnetic and resistivity lows. Pyritic haloes surrounding ore respond well to induced polarization (IP) surveys but in sulfide-poor systems the ore itself provides the only significant IP response. Remote sensing: In areas of good exposure with limited vegetation, airborne and spaceborne multispectral and hyperspectral imaging systems can be used to map alteration mineral associations and their spatial relations in porphyry copper systems. Hydrothermal minerals characteristic of sericitic, intermediate and advanced argillic, and propylitic alteration, iron oxides and hydroxides, and silica can be remotely mapped using their distinctive absorption features in the visible near-infrared through short-wave infrared and thermal-infrared wavelengths',
    },
    'tungsten_skarn': {
        'deposit_type': 'tungsten skarn',
        'synonyms': 'Pyrometasomatic or contact metasomatic tungsten deposits.',
        'commodities': 'W, Mo, Cu, Sn, Zn',
        'description': 'Scheelite-dominant mineralization genetically associated with a skarn gangue.',
        'rock_types': 'Pure and impure limestones, calcareous to carbonaceous pelites. Associated with tonalite, granodiorite, quartz monzonite and granite of both I- and S-types. W skarn-related granitoids, compared to Cu skarn- related plutonic rocks, tend to be more differentiated, more contaminated with sedimentary material, and have crystallized at a deeper structural level.',
        'age_range': 'Mainly Mesozoic, but may be any age.',
        'depositional_environment': 'Contacts and roof pendants of batholith and thermal aureoles of apical zones of stocks that intrude carbonate rocks.',
        'tectonic_setting': 'Continental margin, synorogenic plutonism intruding deeply buried sequences of eugeoclinal carbonate-shale sedimentary rocks. Can develop in tectonically thickened packages in back-arc thrust settings.',
        'ore_mineralogy': 'Scheelite ± molybdenite ± chalcopyrite ±pyrrhotite ± sphalerite ± arsenopyrite ± pyrite ± powellite. May contain trace wolframite, fluorite, cassiterite, galena, marcasite and bornite. Reduced types are characterized by pyrrhotite, magnetite, bismuthinite, native bismuth and high pyrrhotite:pyrite ratios. Variable amounts of quartz-vein stockwork (with local molybdenite) can cut both the exoskarn and endoskarn',
        'alteration': 'Exoskarn alteration: Inner zone of diopside-hedenbergite±grossular-andradite±biotite±vesuvianite, with outer barren wollastonite-bearing zone. An innermost zone of massive quartz may be present. Late stage spessartine±almandine±biotite±amphibole±plagioclase±phlogopite±epidote±fluorite±sphene. Exoskarn envelope can be associated with extensive areas of biotite hornfels. Endoskarn alteration: Pyroxene±garnet±biotite±epidote±amphibole±muscovite±plagioclase±pyrite±pyrrhotite±trace tourmaline and scapolite; local greisen developed.',
        'ore_controls': 'Carbonate rocks in extensive thermal aureoles of intrusions; gently inclined bedding and intrusive contacts; structural and (or) stratigraphic traps in sedimentary rocks and irregular parts of the pluton/country rock contacts.',
        'geochemical_signatures': 'W, Cu, Mo, As, Bi, and B. Less commonly Zn, Pb, Sn, Be, and F.',
        'geophysical_signature': 'Magnetic and induced polarization surveys can be used to outline the surface projection of ore bodies because magnetite, pyrrhotite, and other sulfide minerals are common in these deposits. Although skarns typically have a positive density contrast relative to adjacent intrusions and carbonate rocks, gravity surveys are not commonly used due to high cost and nonspecificity for ore. Remote-sensing techniques can effectively identify carbonate terranes and iron enrichment in skarns if skarn is exposed. In some cases, contacts between intrusions and sedimentary rocks can be mapped and carbonate rocks can be distinguished from noncarbonate rocks.'
    },
    'mvt_zinc_lead': {
        'synonyms': 'Carbonate-hosted Pb-Zn; Mississippi Valley type',
        'description': 'Stratabound, carbonate-hosted deposits of galena, sphalerite, and chalcopyrite in rocks having primary and secondary porosity, commonly related to reefs on paleotopographic highs (see fig. 166). (For grade-tonnage model see Appalachian Zn deposit model.)',
        'rock_types': 'Dolomite; locally ore bodies also occur in sandstone, conglomerate, and calcareous shales.',
        'textures': 'Calcarenites are most common lithology. Tidalites, stromatolite finger reefs, reef breccias, slump breccias; oolites, crossbedding, micrites. ',
        'age_range': 'Known deposits are in Cambrian to Lower Ordovician strata. ',
        'depositional_environment': 'Host rocks are shallow-water marine carbonates, with prominent facies control by reefs growing on flanks of paleotopographic basement highs. Deposits commonly occur at margins of clastic basins. ',
        'tectonic_setting': 'Stable cratonic platform.',
        'mineralogy': 'Galena, sphalerite, chalcopyrite, pyrite, marcasite. Minor siegenite, bornite, tennantite, barite, bravoite, digenite, covellite, arsenopyrite, fletcherite, adularia, pyrrhotite, magnetite, millerite, polydymite, vaesite, djurleite, chalcocite, anilite, and enargite in order of abundance. Dolomite and minor quartz. ',
        'texture': 'Early fine-grained replacement; main stage coarse-grained replacement and vuggy or colloform open space filling. Hypogene leaching of galena is common. ',
        'alteration': 'Regional dolomitization; latter brown, ferroan, and bitumen-rich dolomite; extensive carbonate dissolution and development of residual shale; mixed-layer illite-chlorite altered to 2M muscovite; dickite and kaolinite in vugs; very minor adularia. ',
        'ore_controls': 'Open-space filling and replacement, most commonly at the interface between gray and tan dolomite, but also in traps at any interface between permeable and impermeable units. Any porous units may host ore: sandstone pinchouts; dissolution collapse breccias; faults; permeable reefs; slump, reef, and fault breccias; coarsely crystalline dolostone. ',
        'geochemical_signatures': 'Regional anomalous amounts of Pb, Zn, Cu, Mo, Ag, Co, and Ni in insoluble residues. Zoning is roughly Cu C± Ni ± Co)-Pb-Zn-iron sulfide going up section; ores contain about 30 ppm Ag; inconsistent lateral separation of metal zones. Background for carbonates: Pb = 9 ppm; Zn = 20; Cu = 4.',
    },
    'cu_ni_pge_duluth': {
        'rock_types': 'Peridotite, harzburgite, pyroxenite, norite, augite, troctolite, anorthosite. Associated with pyritic shale, anhydrite, or recognizable source of sulfur to contaminate magma.',
        'textures': 'Cumulus textures, locally diabasic or ophitic textures.',
        'age_range': 'Precambrian to Tertiary(?).',
        'depositional_environment': 'Intruded during rifting into metasedimentary (slate, argillite, graywacke) and metavolcanic rocks.',
        'tectonic_setting': 'Rift environment.',
        'mineralogy': 'Pyrrhotite + pentlandite + chalcopyrite + cubanite ± PGE minerals ± graphite.',
        'texture_structure': 'Disseminated, matrix, and massive sulfides',
        'alteration': 'Locally sulfides may show evidence of hydrothermal remobilization.',
        'ore_controls': 'Zone of active syn-intrusion faulting forming basins, in basal part of intrusion; source of external sulfur; source of silicic material to contaminate magma.',
        'geochemical_signatures': 'Ni/Cu approximately 1/3, Cu, Ni; PGE, Co, Ti; sulfur isotopes show non-magmatic sulfur.',
    },
    'cu_ni_pge_norilsk': {
        'rock_types': 'Flood basalts, picritic intrusive rocks, picritic gabbro, norite, olivine gabbro, dolerite, intrusive and volcanic breccias. Associated with evaporites or some external source of sulfur.',
        'textures': 'Ophitic, subophitic, gabbroic, cumulate.',
        'age_range': 'Paleozoic.',
        'depositional_environment': 'Magma has intruded through evaporites or pyritic shale, and formed sills in flood basalts during active faulting.',
        'tectonic_setting': 'Rift environment.',
        'mineralogy': 'Pyrrhotite + pentlandite + chalcopyrite + cubanite + millerite + vallerite + pyrite + bornite + gersdorffite + sperrylite + PGE alloys + polarite + PGE tellurides, arsenides, and antimonides.',
        'texture_structure': 'Lenses, layers of massive, matrix, and disseminated sulfide.',
        'alteration': 'None related to ore.',
        'ore_controls': 'External source of sulfur; sulfides form persistent basal layers to intrusion and dike-like bodies into country rock; and form in fault-bounded depressions.',
        'geochemical_signatures': 'Ni/Cu = 1.5 to 0.5, Co/Ni = 1/16; Pt/(Pd/Ni) = 1/500',
    },
    'hectorite_li':{
        'synonyms': 'Lithium (Li) smectite, high-Li clay.',
        'commodities': 'Hectorite, Li, bentonite, specialty clays for drilling fluid additives and organoclays.',
        'description': 'Li- and Mg-rich smectite clay; “greasy” when wet, color ranges from bright white to pink pastel to dark-green and brown. Found in playa and caldera sediments.',
        'rock_types': 'Volcanic ash, preexisting smectites, lacustrine sediments in high Mg evaporative lakes.',
        'textures': 'Inherited from parent lacustrine sediments, may be thin or thickly bedded and laterally extensive. Hydrous with “greasy” fresh surface; dries to a blocky texture. Weathered surfaces may develop a “popcorn” texture.',
        'age_range': 'Miocene-Holocene.',
        'depositional_environment': 't Hydrologically closed basin containing evaporative lakes with discharge of geothermal waters. Geothermal waters provide the Li, previously leached from ash and alkaline volcanic rocks.',
        'tectonic_setting': 'Basin-and-Range or other rift settings characterized by rhyolitic volcanism, crustal extension, hydrothermal activity, and high rates of sedimentation',
        'ore_mineralogy': 'Hectorite, saponite, stevensite, bentonite.',
        'alteration': 'Clays may expand with moisture, leading to “popcorn weathering”; lithium may be lost through leaching or cation exchange; burial and diagenesis may convert smectite minerals to illite or chlorite. ',
        'ore_controls': 'Extent of lacustrine sediments, geothermal source of Li',
        'geochemical_signatures': 'Li >300 ppm; ±F, U, Be, B enrichment; high Mg, low Al content',
        'geophysical_signatures': 'Seismic surveys may delineate extent and thickness of lacustrine sediments, and basin depth.',
    },
    'peralkline_carbonatite_ree':{
        'deposit_type': 'Peralkaline and Carbonatite Rare Earth Elements',
        'synonyms': 'REE deposits in peralkaline igneous rocks and carbonatites',
        'commodities': 'REE (La, Ce, Nd, Pr, Sm, Eu, Gd, Tb, Dy, Ho, Er, Tm, Yb, Lu, Y), Nb, Ta, Zr, Hf, Th, U',
        'description': 'These deposits are characterized by the presence of rare earth elements (REE) in peralkaline igneous rocks and carbonatites. They often contain high concentrations of light and heavy REEs, along with other elements such as niobium, tantalum, zirconium, and thorium. The REEs are typically hosted in a variety of minerals, including bastnäsite, monazite, xenotime, and eudialyte.',
        'rock_types': 'Peralkaline syenites, nepheline syenites, phonolites, and carbonatites. Associated with alkaline igneous complexes and carbonatite intrusions.',
        'textures': 'Varies from coarse-grained to fine-grained, often with pegmatitic textures. Carbonatites may exhibit banded or brecciated textures.',
        'age_range': 'Primarily Proterozoic to Phanerozoic, but can be any age.',
        'depositional_environment': 'Intrusive complexes, often associated with rift zones or other extensional tectonic settings. Carbonatites typically form as small, isolated intrusions or as part of larger alkaline igneous complexes.',
        'tectonic_setting': 'Commonly associated with continental rift zones, intraplate settings, and other extensional environments. These settings facilitate the emplacement of alkaline magmas and carbonatites.',
        'ore_mineralogy': 'Bastnäsite, monazite, xenotime, eudialyte, loparite, parisite, synchysite, pyrochlore, columbite-tantalite, zircon, baddeleyite, thorite, and uraninite.',
        'alteration': 'Hydrothermal alteration is common, including fenitization (alkali metasomatism) around carbonatite intrusions. Alteration minerals may include aegirine, riebeckite, alkali feldspar, and carbonate minerals.',
        'ore_controls': 'Structural controls such as faults and fractures are important for the emplacement of peralkaline and carbonatite magmas. The presence of pre-existing alkaline igneous complexes can also localize mineralization.',
        'geochemical_signatures': 'High concentrations of REEs, Nb, Ta, Zr, Hf, Th, and U. Geochemical anomalies in light and heavy REEs, often with elevated levels of fluorine, phosphorus, and barium.',
        'geophysical_signatures': 'Magnetic and radiometric surveys can be effective in identifying these deposits due to the presence of magnetic minerals and radioactive elements (e.g., thorium and uranium). Gravity surveys may also be useful in delineating dense carbonatite bodies. Remote sensing techniques can help identify alteration zones and structural features associated with these deposits.',
    },
    'carbonatite':{
        'synonyms': 'Apatite-magnetite  and  rare  earths  in  carbonatites',
        'description': 'Apatite-magnetite  and  rare-earth  deposits  and  combinations  of  these  in  zoned  complexes consisting of central plug of carbonatite or syenite breccia surrounded by ring dikes and conesheets of alternating rock types',
        'rock_types': 'Apatite-magnetite deposits tend to be in sovite (calcitic carbonatite); RE types tend to occur in ankerite carbonatite; most deposits have both. In general pyroxenite, nepheline and feldspathic  pyroxenite,  carbonatite,  fenite,  ijolite,  dunite,  picrite-porphyrites,  gneiss  and alkalic fenitized gneiss, and locally alkaline volcanics rocks',
        'textures': 'Hypidiomorphic-granular,  poikiloblastic.  Breccias  abundant. Carbonatites  show  intrusive relations. Wallrocks  fenitized',
        'age_range': ' Almost  all  known  carbonatite  complexes  are  intrusive  into  Precambrian  shields,  however, the carbonatites themselves may be much younger',
        'depositional_environment': 'Multiple stages of igneous, deuteric  and  metasomatic  crystallization  in carbonatite magma.',
        'tectonic_setting': 'Continental shields. Spatially related to fault lineaments such as East African rift system. Locally related to alkaline volcanism',
        'mineralogy': 'Apatite-magnetite-type: apatite, magnetite, pyrochlore ± columbite ± perovskite ± niocalite. RE-type: barite,  strontianite  ±  siderite  ±  rhodochrosite  ±  ankerite  ±  bastnaesite  ± chlorites ± parisite ± monagite ± breunnerite. General: calcite, dolomite, fluorite, pyrhotite, ilmenite,  molybdenite,  chalcopyrite,  pyrite,  sphalerite, pyroxene,  biotite,  phlogopite,  amphibole, spinel, ± galena, ± hematite, ± quartz, ± forsterite, ± serpentine, ± zircon ± sphene, ± anatase, ±rutile, ± brookite, ± fersmite',
        'structure': 'Disseminated and banded',
        'alteration': 'Fenitization  (widespread  alkali  metasomatism  of  quartzo-feldspathic  rock;  mostly alkalic  feldspar  with  some  aegerine  and  subordinate  alkali-hornblende  and  accessory  sphene  andapatite) near contact of carbonatite intrusion. Locally,  chloritization.',
        'ore_controls': 'Commonly  restricted  to  carbonatite  dikes,  sills,  breccias,  sheets,  veins,  and  large masses, but may occur in other rocks associated with the complex rocks',
        'geochemical_signatures': 'Radiometric anomalies, magnetic anomalies, high gravity anomalies, Th, U, Ti, Zn, Nb, Y, Ce, Mo, Cu, V, P, Mn, S, La, Sm, Pb, Zr, Ba, Eu. High values of Be, B, Li, Sn, Ta, Hf, and W are rare.'
    },
}