[theme]
#primaryColor="#0550c4"
primaryColor="F06E32"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"

[server]
maxMessageSize = 500
maxUploadSize = 500

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[global]
disableWidgetStateDuplicationWarning = true